repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check . --fix --exit-non-zero-on-fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: ruff format . 
        language: system
        pass_filenames: false